### ISSUE TITLE
TODO: Feature parity with `R`

### ISSUE THREAD

**Issue by vincentarelbundock** [vincentarelbundock/pymarginaleffects#1]
+ [x] `datagridcf())`
+ [x] `plot_*()` (low priority)
+ [ ] `inferences()` (very low priority)
  - [ ] conformal inference
+ [x] `hypothesis` float sets the NULL
+ [ ] `comparison` argument accepts lambda functions
+ [ ] `numderiv` with different jacobians. Richardson probably requires GPL since the code is translated from `numDeriv`
+ [ ] hypothesis = "drat = 2 * qsec" using text term names
+ [ ] convert R tests
